=== mdicpal/blackhorse/evo.funders.commonmessages/v1/CommonRequest.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/CommonRequest",
    "$version": 1,
    "definitions": {
        "CommonRequest": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "requestType": {
                    "enum": ["MakeApplication", "GetEsign", "AdditionalData", "GetQuote", "DocumentUpload"]
                },
                "quoteId": {
                    "type": "integer"
                },
                "funderCode": {
                    "type": ["integer","string"]
                },
                "version": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                }
            },
            "required": [
                "data",
                "funderCode",
                "quoteId",
                "requestType",
                "version"
            ],
            "title": "CommonRequest"
        }
    }
}

=== mdicpal/blackhorse/evo.funders.commonmessages/v1/UnitTests/TestData/MakeApplication/valid/no-mobtel-main.json
{
  "requestType": "MakeApplication",
  "quoteId": 509,
  "funderCode": "V12",
  "version": 1,
  "data": {
    "applicants": [
      {
        "isMainApplicant": true,
        "applicantType": "Personal",
        "title": "Mr",
        "forename": "Test",
        "middlename": "Middle",
        "surname": "User",
        "dob": "1988-03-18",
        "sexAtBirth": "m",
        "maritalStatus": "Single",
        "isUkResident": true,
        "homephone": "01215431289",
        "mobile":null,
        "email": "test@evolutionfunding.com",
        "drivingLicenceType": "UK Full",
        "nationality": "British",
        "residenceHistory": [
          {
            "address": {
              "unit": "TestSubBuilding",
              "houseName": "Test",
              "houseNumber": "1",
              "addressLine1": "Doe Lane",
              "addressLine2": "",
              "addressLine3": "",
              "town": "Chesterfield",
              "county": "Test County",
              "postcode": "S419AZ"
            },
            "orderNumber": 1,
            "residentialStatusShortcode": "Owner",
            "yearsAtAddress": 17,
            "monthsAtAddress": 9
          }
        ],
        "employmentHistory": [
          {
            "orderNumber": 1,
            "occupationType": "Accountancy",
            "jobTitle": "Tester",
            "company": "EvolutionFundingLtd",
            "yearsAtCompany": 9,
            "monthsAtCompany": 3,
            "employmentType": "Full time",
            "employmentStatus": "Employed",
            "phoneNumber": "0215678648",
            "address": {
              "unit": "",
              "houseName": "",
              "houseNumber": "",
              "addressLine1": "Thompson Close",
              "addressLine2": "",
              "addressLine3": "",
              "town": "Chesterfield",
              "county": "",
              "postcode": "S419AZ"
            }
          },
          {
            "orderNumber": 2,
            "jobTitle": "Tester",
            "company": "EvolutionFundingLtd2",
            "yearsAtCompany": 10,
            "monthsAtCompany": 4,
            "phoneNumber": null
          }
        ],
        "financialStatus": {
          "annualGrossIncome": 20000,
          "affordability": "Affordable",
          "affordabilityReason": "ExampleReason",
          "affordabilityMonthlyMortgageRentContribution": 100
        },
        "bank": {
          "accountName": "Test User",
          "bankName": "NATIONWIDE BUILDING SOCIETY",
          "address": {
            "addressLine1": "P.O. Box 8888",
            "addressLine2": "Nationwide Hse",
            "addressLine3": "Pipers Way",
            "town": "Swindon L",
            "county": "Wilts.",
            "postcode": "SN38 1NW"
          },
          "accountNumber": "10909132",
          "sortCode": "070116",
          "years": "15",
          "months": "4"
        },
        "marketingPreference": {
          "optInEmail": true,
          "optInSms": true,
          "optInPhone": true,
          "optInPost": true
        }
      }
    ],
    "dealer": {
      "dealerId": "6859",
      "groupId": null,
      "dealerCode": "6859",
      "dealerGroupCode": null,
      "isMccWeblead": false,
      "commissionType": "FRP Enhanced",
      "dealerPackageCode": null
    },
    "quote": {
      "isBusinessQuote": false,
      "quoteDate": "2023-03-22",
      "annualMileage": 10000,
      "partExchange": 1000,
      "settlement": 123,
      "deposit": 2000,
      "flatRate": 5.3,
      "term": 24,
      "vehicleCashPrice": 7706.67,
      "isVehicleVatQualifying": false,
      "balloonValue": 0,
      "financeType": "HP",
      "apr": 10.33,
      "isDistanceSold": false,
      "settlementMonthlyAmount": 0,
      "experianCountyCourtJudgments": 0,
      "experianDefaults": 0,
      "equifaxCountyCourtJudgments": 0,
      "equifaxDefaults": 0
    },
    "asset": {
      "make": "BMW",
      "model": "4 SERIES DIESEL COUPE",
      "style": "430d M Sport 2dr Auto",
      "assetType": "Car",
      "isNew": false,
      "vrm": "WO14LWN",
      "vin": "1HGBH41JXMN109186",
      "capCode": "BM4S303MT2CDTA",
      "currentMileage": 10365,
      "registrationDate": "2014-08-06"
    }
  }
}

=== mdicpal/blackhorse/UnitTests/DomainLayerTests/FunderService/Mappers/TestData/MickeyMouse.json
{
  "requestType": "MakeApplication",
  "quoteId": 90155,
  "funderCode": "OODLEV2",
  "version": 1,
  "data": {
    "applicants": [
      {
        "isMainApplicant": true,
        "applicantType": "Personal",
        "title": "Mr",
        "forename": "Mickey",
        "middlename": "",
        "surname": "Mouse",
        "dob": "1968-01-01",
        "sexAtBirth": "m",
        "maritalStatus": "Married",
        "isUkResident": true,
        "homephone": "01511112222",
        "mobile": "07777666555",
        "email": "mickey.mouse@gmail.com",
        "drivingLicenceType": "UK Full",
        "nationality": "British",
        "residenceHistory": [
          {
            "address": {
              "unit": "",
              "houseName": "",
              "houseNumber": "12",
              "addressLine1": "Coney Green Way",
              "addressLine2": "",
              "addressLine3": "",
              "town": "Telford",
              "county": "",
              "postcode": "TF13QZ"
            },
            "orderNumber": 1,
            "residentialStatusShortcode": "Owner",
            "yearsAtAddress": 43,
            "monthsAtAddress": 5
          }
        ],
        "employmentHistory": [
          {
            "orderNumber": 1,
            "occupationType": "Other",
            "jobTitle": "Entertainer",
            "company": "Disney Corp",
            "yearsAtCompany": 43,
            "monthsAtCompany": 5,
            "employmentType": "Full time",
            "employmentStatus": "Employed",
            "phoneNumber": "00000000000",
            "address": {
              "unit": "",
              "houseName": "",
              "houseNumber": "",
              "addressLine1": "Thompson Close",
              "addressLine2": "",
              "addressLine3": "",
              "town": "Telford",
              "county": "",
              "postcode": "S419AZ"
            }
          }
        ],
        "financialStatus": {
          "annualGrossIncome": 25000,
          "affordability": "Unknown",
          "affordabilityMonthlyMortgageRentContribution": 500,
          "netMonthlyIncome": 1709
        },
        "bank": {
          "accountName": "Mickey Mouse",
          "bankName": "LLOYDS BANK PLC",
          "address": {
            "addressLine1": "PO Box 1000",
            "addressLine2": "",
            "addressLine3": "",
            "town": "",
            "county": "",
            "postcode": "BX1 1LT"
          },
          "accountNumber": "31000000",
          "sortCode": "300000",
          "years": "10",
          "months": "10"
        },
        "marketingPreference": {
          "optInEmail": true,
          "optInSms": false,
          "optInPhone": false,
          "optInPost": false
        }
      }
    ],
    "dealer": {
      "dealerId": "6859",
      "groupId": null,
      "dealerCode": "6859",
      "dealerGroupCode": null,
      "isMccWeblead": false,
      "commissionType": "Credit Score Based Pricing",
      "dealerPackageCode": null
    },
    "quote": {
      "isBusinessQuote": false,
      "quoteDate": "2023-07-03",
      "annualMileage": 30824,
      "partExchange": 0,
      "settlement": 0,
      "deposit": 5000,
      "flatRate": 0.44,
      "term": 60,
      "vehicleCashPrice": 21000,
      "isVehicleVatQualifying": false,
      "balloonValue": 0,
      "financeType": "HP",
      "apr": 0.86,
      "isDistanceSold": false,
      "settlementMonthlyAmount": 0,
      "experianCountyCourtJudgments": 0,
      "experianDefaults": 0,
      "equifaxCountyCourtJudgments": 0,
      "equifaxDefaults": 0
    },
    "asset": {
      "isCreditLimitVehicle": false,
      "make": "BMW",
      "model": "4 SERIES GRAN DIESEL COUPE",
      "style": "420d [190] xDrive Sport 5dr Auto [Business Media]",
      "assetType": "Car",
      "isNew": false,
      "vrm": "ST18EFW",
      "vin": "WBA4K52020BE94002",
      "capCode": "BM4S20PB95HDTA4",
      "currentMileage": 30824,
      "registrationDate": "2018-03-30"
    },
    "dispersalOptions": []
  }
}
